services:
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend.Dockerfile.dev
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/src:/app/src
      - ./backend/prisma:/app/prisma
    command: npm run dev
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - node_modules/
            - dist/
        - action: rebuild
          path: ./backend/package.json

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend.Dockerfile.dev
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend/app:/app/app
      - ./frontend/components:/app/components
      - ./frontend/styles:/app/styles
      - ./frontend/public:/app/public
    command: npm run dev
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/
            - .next/
        - action: rebuild
          path: ./frontend/package.json
