services:
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend.Dockerfile.prod
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend.Dockerfile.prod
    env_file:
      - ./frontend/.env
    restart: unless-stopped
